---
title: "wk5_homework"
output: html_document
date: "2023-11-15"
---
Homework-Difference in Inequality between 2010 and 2019
```{r}
library(sf)
library(RSQLite)
library(tidyverse)
library(dplyr)
library(tmap)
library(tmaptools)
```
read in the shapefile
```{r}
shape <- st_read("World_Countries_Generalized.shp")
```
read in the csv
```{r}
mycsv <- read_csv("HDR21-22_Composite_indices_complete_time_series.csv") 
```
select gii 2010-2019
```{r}
gii2010to2019 <- mycsv %>%
  dplyr::select(contains("country"),contains("gii_2010"),contains("gii_2011"),
                contains("gii_2012"),contains("gii_2013"),contains("gii_2014"),
                contains("gii_2015"),contains("gii_2016"),contains("gii_2017"),
                contains("gii_2018"),contains("gii_2019"))
```
write in world map
```{r}
WorldMapgii <- shape %>% 
  left_join(., 
            gii2010to2019,
            by = c("COUNTRY" = "country"))
frames <- list()
```
create difference map
```{r}
Dif2010to2019 <- WorldMapgii%>%
  mutate(dif=gii_2019-gii_2010)%>%
  mutate(difcompare=case_when(dif >= 0 ~ "increase", TRUE ~ "decrease"))
Difmap <- tm_shape(Dif2010to2019) + 
  tm_borders() + 
  tm_fill("difcompare",title = "Difference in Inequality between 2010 and 2019") +
  tm_layout(legend.position = c("left","bottom"), legend.text.size = 0.6)
Difmap
```
create changing maps
```{r}
tmap_mode("plot")
breaks <- c(0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)
for (year in 2010:2019) {
  giimap <- tm_shape(WorldMapgii) + 
    tm_borders() + 
    tm_fill(paste("gii_", year, sep = ""), breaks = breaks, palette = "Reds") +
    tm_layout(legend.position = c("left", "center"), legend.text.size = 0.6)
  frames[[year - 2009]] <- giimap
}
```
create gif
```{r}
giimaps <- tmap_animation(
  frames,
  filename = "giimap2010to2019.gif",
  width = 800,
  height = 600,
  delay = 100
)
```


